import Head from "next/head";
import TagInput from "../components/TagInput";
import { GlobalStyle } from "../styles/GlobalStyle";
import { TagInputUiStyled } from "../styles/TagInputUI";

export default function Home() {
  return (
    <>
      <GlobalStyle />
      <Head>
        <title>Alibaba | Tag Input code challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TagInputUiStyled>
        <TagInput />
      </TagInputUiStyled>
    </>
  );
}
